import type { DomSnapshot } from '../src/types/dom.js';
import type { LocatorReport } from '../src/types/locator.js';
import type { SelectorValidationReport } from '../src/types/validation.js';
import type { DomComparisonReport } from '../src/types/comparison.js';
import type { DiagnosticEvidenceManifest } from '../src/types/diagnostics.js';
import type { SelectorRepairReport } from '../src/types/repair.js';
import type { MonitorHistoryReport } from '../src/types/monitoring.js';

const generatedAt = '2026-07-18T12:00:00.000Z';

export function discoveryFixture(): DomSnapshot {
  return {
    schemaVersion: '1.0',
    toolkitVersion: '0.12.0',
    capturedAt: generatedAt,
    requestedUrl: 'https://example.com/?token=redacted',
    finalUrl: 'https://example.com/',
    title: 'Example',
    options: {
      scope: 'interactive',
      includeHidden: false,
      maxElements: 100,
      maxFrameDepth: 4,
      textLimit: 200,
      redact: true,
    },
    summary: {
      frameCount: 1,
      failedFrameCount: 0,
      shadowRootCount: 0,
      inspectedElementCount: 1,
      matchedElementCount: 1,
      visibleElementCount: 1,
      hiddenElementCount: 0,
      interactiveElementCount: 1,
      sensitiveElementCount: 0,
      redactionCount: 1,
      truncated: false,
      kinds: { button: 1 },
    },
    frames: [
      {
        path: 'main',
        parentPath: null,
        depth: 0,
        index: 0,
        name: null,
        url: 'https://example.com/',
        title: 'Example',
        language: 'en',
        readyState: 'complete',
        shadowRootCount: 0,
        inspectedElementCount: 1,
        matchedElementCount: 1,
        truncated: false,
        elements: [
          {
            id: 'element-1',
            framePath: 'main',
            shadowPath: [],
            domPath: 'html > body > button:nth-of-type(1)',
            tagName: 'button',
            kind: 'button',
            role: 'button',
            accessibleName: 'Submit <script>alert(1)</script>',
            text: 'Submit',
            label: null,
            placeholder: null,
            attributes: { id: 'submit' },
            visibility: {
              visible: true,
              reason: 'visible',
              inViewport: true,
              boundingBox: { x: 0, y: 0, width: 100, height: 40 },
            },
            interactive: true,
            interactivitySources: ['native-control'],
            disabled: false,
            readonly: false,
            required: false,
            checked: null,
            selected: null,
            sensitive: false,
            redactionsApplied: 0,
          },
        ],
      },
    ],
    failures: [],
    warnings: [],
  };
}

export function locatorFixture(): LocatorReport {
  return {
    schemaVersion: '1.1',
    toolkitVersion: '0.12.0',
    generatedAt,
    requestedUrl: 'https://example.com/',
    finalUrl: 'https://example.com/',
    title: 'Example',
    options: {
      maxCandidatesPerElement: 8,
      includeXPath: true,
      includeRoleWithoutName: false,
      testIdAttributes: ['data-testid'],
      liveTest: true,
      minimumRecommendedScore: 60,
    },
    domSummary: discoveryFixture().summary,
    summary: {
      elementCount: 1,
      candidateCount: 2,
      testedCandidateCount: 2,
      uniqueCandidateCount: 1,
      multipleCandidateCount: 1,
      missingCandidateCount: 0,
      errorCandidateCount: 0,
      elementsWithUniqueCandidate: 1,
      elementsWithoutCandidates: 0,
      strategies: { role: 1, text: 1 },
      recommendedLocatorCount: 1,
      elementsWithRecommendation: 1,
      elementsWithoutRecommendation: 0,
      highConfidenceCandidateCount: 1,
      mediumConfidenceCandidateCount: 0,
      lowConfidenceCandidateCount: 1,
      averageStabilityScore: 70,
    },
    elements: [],
    failures: [],
    warnings: [],
    recommendations: [
      {
        elementId: 'element-1',
        elementKind: 'button',
        framePath: 'main',
        playwright: "page.getByRole('button', { name: 'Submit' })",
        strategy: 'role',
        score: 92,
        confidence: 'high',
      },
    ],
  };
}

export function validationFixture(): SelectorValidationReport {
  return {
    schemaVersion: '1.0',
    toolkitVersion: '0.12.0',
    generatedAt,
    manifestPath: '/tmp/selectors.yaml',
    manifestName: 'Login selectors',
    requestedUrl: 'https://example.com/',
    finalUrl: 'https://example.com/',
    title: 'Example',
    summary: {
      total: 2,
      required: 1,
      optional: 1,
      passed: 1,
      failed: 1,
      errors: 0,
      requiredFailures: 0,
      optionalFailures: 1,
      success: true,
    },
    results: [
      {
        id: 'submit',
        name: 'Submit',
        required: true,
        framePath: 'main',
        locator: { type: 'role', role: 'button', name: 'Submit', exact: true },
        playwright: "page.getByRole('button', { name: 'Submit', exact: true })",
        status: 'pass',
        observed: { count: 1, visibleCount: 1, enabledCount: 1, editableCount: 0, durationMs: 3 },
        assertions: [
          {
            assertion: 'count',
            status: 'pass',
            expected: '1',
            actual: 1,
            message: 'Matched exactly 1 element',
          },
        ],
        error: null,
      },
      {
        id: 'banner',
        name: 'Optional banner',
        required: false,
        framePath: 'main',
        locator: { type: 'css', selector: '.banner' },
        playwright: "page.locator('.banner')",
        status: 'fail',
        observed: { count: 0, visibleCount: 0, enabledCount: 0, editableCount: 0, durationMs: 2 },
        assertions: [
          {
            assertion: 'count',
            status: 'fail',
            expected: '1',
            actual: 0,
            message: 'Expected one banner',
          },
        ],
        error: null,
      },
    ],
    warnings: [],
  };
}

export function comparisonFixture(): DomComparisonReport {
  return {
    schemaVersion: '1.0',
    toolkitVersion: '0.12.0',
    generatedAt,
    baseline: {
      name: 'login',
      version: 'v1',
      capturedAt: generatedAt,
      finalUrl: 'https://example.com/',
      title: 'Before',
    },
    current: { capturedAt: generatedAt, finalUrl: 'https://example.com/', title: 'After' },
    options: {
      similarityThreshold: 0.65,
      includeUnchanged: false,
      maxReplacementLocators: 5,
      minimumLocatorScore: 60,
    },
    summary: {
      baselineElementCount: 1,
      currentElementCount: 1,
      matchedElementCount: 0,
      unchangedElementCount: 0,
      addedElementCount: 1,
      removedElementCount: 1,
      movedElementCount: 0,
      changedElementCount: 0,
      movedAndChangedElementCount: 0,
      driftElementCount: 2,
      driftDetected: true,
      matchMethods: { structural: 0, semantic: 0, similarity: 0 },
    },
    differences: [
      {
        kind: 'removed',
        baseline: {
          elementId: 'old',
          framePath: 'main',
          shadowPath: [],
          domPath: 'body > button',
          tagName: 'button',
          kind: 'button',
          role: 'button',
          accessibleName: 'Old button',
          label: null,
          placeholder: null,
          attributes: {},
          visible: true,
        },
      },
      {
        kind: 'added',
        current: {
          elementId: 'new',
          framePath: 'main',
          shadowPath: [],
          domPath: 'body > button',
          tagName: 'button',
          kind: 'button',
          role: 'button',
          accessibleName: 'New button',
          label: null,
          placeholder: null,
          attributes: {},
          visible: true,
        },
        replacementLocators: [
          {
            playwright: "page.getByRole('button', { name: 'New button' })",
            strategy: 'role',
            score: 90,
            confidence: 'high',
            rationale: 'Semantic role',
            warnings: [],
          },
        ],
      },
    ],
    warnings: [],
  };
}

export function diagnosticFixture(): DiagnosticEvidenceManifest {
  return {
    schemaVersion: '1.0',
    toolkitVersion: '0.12.0',
    createdAt: generatedAt,
    success: false,
    requestedUrl: 'https://example.com/',
    finalUrl: 'https://example.com/',
    title: 'Evidence',
    navigation: null,
    metadata: null,
    recorder: {
      schemaVersion: '1.0',
      capturedAt: generatedAt,
      console: [{ timestamp: generatedAt, type: 'warning', text: 'Warning text', location: null }],
      pageErrors: [{ timestamp: generatedAt, name: 'Error', message: 'Page failed', stack: null }],
      requestFailures: [],
      httpErrors: [],
      summary: {
        consoleEntryCount: 1,
        pageErrorCount: 1,
        requestFailureCount: 0,
        httpErrorCount: 0,
        droppedConsoleEntries: 0,
        droppedPageErrors: 0,
        droppedRequestFailures: 0,
        droppedHttpErrors: 0,
        redactionCount: 0,
      },
    },
    screenshots: {
      artifacts: [
        {
          kind: 'viewport',
          path: '/tmp/run/screenshots/viewport.png',
          selector: null,
          matchIndex: null,
          width: 1,
          height: 1,
        },
      ],
      failures: [],
    },
    files: {
      metadata: 'reports/page-metadata.json',
      events: 'reports/diagnostic-events.json',
      domSnapshot: null,
      htmlSnapshot: null,
      htmlFrames: [],
      screenshots: ['screenshots/viewport.png'],
      trace: 'traces/trace.zip',
    },
    failure: { name: 'Error', message: 'Controlled failure', stack: null },
    warnings: [],
  };
}

export function repairFixture(): SelectorRepairReport {
  return {
    schemaVersion: '1.0',
    toolkitVersion: '0.15.0',
    generatedAt,
    manifestPath: '/tmp/selectors.yaml',
    manifestName: 'Login selectors',
    requestedUrl: 'https://example.com/login',
    finalUrl: 'https://example.com/login',
    title: 'Login',
    provider: 'none',
    model: null,
    summary: {
      manifestSelectorCount: 2,
      failedSelectorCount: 2,
      requiredFailureCount: 2,
      optionalFailureCount: 0,
      selectorsWithSuggestions: 2,
      selectorsWithRecommendation: 1,
      unresolvedRequiredCount: 1,
      unresolvedOptionalCount: 0,
      aiAssistedCount: 0,
      approvalRequired: true,
    },
    validationSummary: {
      total: 2,
      required: 2,
      optional: 0,
      passed: 0,
      failed: 2,
      errors: 0,
      requiredFailures: 2,
      optionalFailures: 0,
      success: false,
    },
    repairs: [
      {
        selector: {
          id: 'submit',
          name: 'Sign in button',
          required: true,
          framePath: 'main',
          locator: { type: 'role', role: 'button', name: 'Log in', exact: true },
          assertions: { count: 1, visible: 'all', enabled: 'all' },
        },
        validation: {
          id: 'submit',
          name: 'Sign in button',
          required: true,
          framePath: 'main',
          locator: { type: 'role', role: 'button', name: 'Log in', exact: true },
          playwright: "page.getByRole('button', { name: 'Log in', exact: true })",
          status: 'fail',
          observed: { count: 0, visibleCount: 0, enabledCount: 0, editableCount: 0, durationMs: 2 },
          assertions: [],
          error: null,
        },
        suggestions: [
          {
            id: 'submit:candidate',
            candidateId: 'element-1:role',
            locator: { type: 'role', role: 'button', name: 'Sign in', exact: true },
            playwright: "page.getByRole('button', { name: 'Sign in', exact: true })",
            strategy: 'role',
            score: 91,
            confidence: 'high',
            source: 'deterministic',
            element: {
              elementId: 'element-1',
              framePath: 'main',
              shadowPath: [],
              tagName: 'button',
              kind: 'button',
              role: 'button',
              accessibleName: 'Sign in',
              label: null,
              placeholder: null,
              visible: true,
            },
            reasons: ['Unique semantic role and accessible name.'],
            warnings: [],
            aiConfidence: null,
            aiRationale: null,
          },
        ],
        recommendedSuggestionId: 'submit:candidate',
        unresolvedReason: null,
      },
      {
        selector: {
          id: 'missing-field',
          name: 'Missing field',
          required: true,
          framePath: 'main',
          locator: { type: 'css', selector: '#missing' },
          assertions: { count: 1 },
        },
        validation: {
          id: 'missing-field',
          name: 'Missing field',
          required: true,
          framePath: 'main',
          locator: { type: 'css', selector: '#missing' },
          playwright: "page.locator('#missing')",
          status: 'fail',
          observed: { count: 0, visibleCount: 0, enabledCount: 0, editableCount: 0, durationMs: 2 },
          assertions: [],
          error: null,
        },
        suggestions: [],
        recommendedSuggestionId: null,
        unresolvedReason: 'No unique live locator candidates matched this selector.',
      },
    ],
    proposalPath: 'reports/selector-repair-proposal.yaml',
    approvalRequired: true,
    warnings: [],
  };
}

export function monitoringHistoryFixture(): MonitorHistoryReport {
  return {
    schemaVersion: '1.0',
    monitorName: 'Production',
    generatedAt,
    manifestPath: '/tmp/monitor.yaml',
    historyPath: '/tmp/history.jsonl',
    reportPath: '/tmp/run/reports/monitor-history.json',
    artifactRun: {
      id: 'history',
      command: 'monitor-history',
      createdAt: generatedAt,
      directories: {
        root: '/tmp',
        run: '/tmp/run',
        screenshots: '/tmp/run/screenshots',
        snapshots: '/tmp/run/snapshots',
        traces: '/tmp/run/traces',
        reports: '/tmp/run/reports',
      },
      metadataPath: '/tmp/run/run.json',
    },
    window: {
      since: '2026-07-01T00:00:00.000Z',
      until: '2026-07-18T00:00:00.000Z',
      durationMs: 17 * 86_400_000,
    },
    summary: {
      recordCount: 12,
      targetCount: 1,
      checks: 12,
      healthyChecks: 10,
      unhealthyChecks: 2,
      passRatePercent: 83.333,
      estimatedAvailabilityPercent: 99.5,
      incidentCount: 1,
      resolvedIncidentCount: 1,
      openIncidentCount: 0,
      meanTimeToRecoveryMs: 60_000,
      longestOutageMs: 60_000,
      averageCheckDurationMs: 125,
    },
    targets: [
      {
        targetId: 'login',
        targetName: 'Login',
        checks: 12,
        healthyChecks: 10,
        unhealthyChecks: 2,
        passRatePercent: 83.333,
        estimatedAvailabilityPercent: 99.5,
        incidentCount: 1,
        resolvedIncidentCount: 1,
        openIncidentCount: 0,
        meanTimeToRecoveryMs: 60_000,
        meanTimeBetweenFailuresMs: null,
        longestOutageMs: 60_000,
        averageCheckDurationMs: 125,
        p50CheckDurationMs: 100,
        p95CheckDurationMs: 250,
        firstCheckedAt: '2026-07-01T00:00:00.000Z',
        lastCheckedAt: '2026-07-18T00:00:00.000Z',
      },
    ],
    daily: [
      {
        date: '2026-07-18',
        checks: 2,
        healthyChecks: 1,
        unhealthyChecks: 1,
        passRatePercent: 50,
        averageDurationMs: 125,
        incidentEvents: 1,
      },
    ],
    incidents: [
      {
        incidentId: 'incident-1',
        targetId: 'login',
        openedAt: '2026-07-18T00:00:00.000Z',
        resolvedAt: '2026-07-18T00:01:00.000Z',
        durationMs: 60_000,
        peakSeverity: 'high',
        open: false,
      },
    ],
  };
}
